version: '3.9'

services:

  # --- MongoDB ---
  mongodb:
    image: mongo:7
    container_name: recettes_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: recette
    ports:
      - "27017:27017"
    networks:
      - recettes_net
    volumes:
      - mongodb_data:/data/db

  # --- Mongo Express (UI MongoDB) ---
  mongo-express:
    image: mongo-express
    container_name: recettes_mongo_express
    restart: unless-stopped
    ports:
      - "8087:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongodb
    networks:
      - recettes_net

  # --- Backend Node.js ---
  recettes_back:
    build:
      context: ./recettes_back
      dockerfile: Dockerfile
    container_name: recettes_back
    restart: unless-stopped
    env_file:
      - ./recettes_back/.env
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    networks:
      - recettes_net

  # --- Frontend ---
  recettes_front:
    build:
      context: ./recettes_front
      dockerfile: Dockerfile
    container_name: recettes_front
    restart: unless-stopped
    ports:
      - "8005:80"
    depends_on:
      - recettes_back
    networks:
      - recettes_net

# --- Réseau partagé ---
networks:
  recettes_net:
    driver: bridge

# --- Volumes ---
volumes:
  mongodb_data:
